### ISSUE TITLE
consistent attribute access

### ISSUE THREAD

**Issue by malwarefrank** [malwarefrank/dnfile#20]
Objects' attributes throughout the project should be accessed consistently to reduce cognitive load on developers and library users.

Right now some objects have attributes that are set to None when there is a parse error, while others are not set at all.

**Comment by malwarefrank** [comment]
Do getattr/hasattr arguments auto-complete in IDEs, or do developers have to recall exact names of attributes when using getattr/hasattr?

**Comment by williballenthin** [comment]
> Do getattr/hasattr arguments auto-complete in IDEs, or do developers have to recall exact names of attributes when using getattr/hasattr?

The latter. I'm not aware of any IDEs that can autocomplete property names passed to `getattr()`.

**Comment by williballenthin** [comment]
survey of uses of `setattr`:

set `IMAGE_DIRECTORY_ENTRY` on pe instance
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/__init__.py#L171-L176

set `DIRECTORY_ENTRY_COM_DESCRIPTOR` on pe instance
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/__init__.py#L205-L211

set flag and mask properties on `ClrFlags` instances
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/enums.py#L44-L54
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/enums.py#L93

add shortcut to table by name:
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/stream.py#L363-L365

### `MDTableRow` properties

`MDTableRow` `struct_asis` properties
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/base.py#L221-L223

`MDTableRow` `struct_strings` properties
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/base.py#L234-L235

`MDTableRow` `struct_guids` properties
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/base.py#L251-L252

`MDTableRow` `struct_blobs` properties
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/base.py#L263-L264

`MDTableRow` `struct_codedindexes` properties
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/base.py#L275-L276

`MDTableRow` `struct_flags` properties
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/base.py#L290

`MDTableRow` `struct_enums` properties
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/base.py#L304

`MDTableRow` `struct_indexes` properties
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/base.py#L316-L318

`MDTableRow` `struct_lists` properties
https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/base.py#L361-L366

**Comment by williballenthin** [comment]
my personal intuition might be:
  - don't set attribute when parsing is proceeding well and the underlying element "doesn't exist". 
  - set attributes to `None` to indicate a parsing error. users can rely on properties, such as `MDTableRow` `struct_index` fields, to exist and autocomplete, and should check for `None` to indicate parsing errors.

given the above, code should be added to set `MDTableRow` properties to `None` upon failure. flags and masks properties should probably be updated to `False` when unset. PE directories shouldn't be set if they're not present (so existing behavior). i'm not sure about the table shortcuts; using a construct like `"MethodDef" in dn.net.tables` seems idiomatic.

**Comment by malwarefrank** [comment]
I think auto-completion is best and am implementing default values as mentioned above.  Willing to see evidence to the contrary until v1.0, at which point I want the API to be locked down and no breaking changes within a major version.
