### ISSUE TITLE
push v0.11.2 to PyPI

### ISSUE THREAD

**Issue by mike-hunhoff** [malwarefrank/dnfile#58]
looks like you tagged v0.11.2 but PyPI still hosts v0.11.0. Could you please push v0.11.2 to PyPI? we would love to pull in your recent changes, thank you!

**Comment by malwarefrank** [comment]
updating the history file now and will push a new version shortly.  This'll be a good test of the github action I set up :)

**Comment by malwarefrank** [comment]
done!

**Comment by mike-hunhoff** [comment]
@malwarefrank you rock, thank you!
