### ISSUE TITLE
MethodList list is empty if type has exactly one method

### ISSUE THREAD

**Issue by heck-gd** [malwarefrank/dnfile#78]
We found an issue where, if a type has exactly one method (e.g., a `cctor`), the logic that fills the list exits prematurely due to a bug.

This line is responsible:
https://github.com/malwarefrank/dnfile/blob/366aa880ea1944085f82e4b0c0400f2f8ab4e88f/src/dnfile/base.py#L463

For example, if the `MethodList` index is 122 and the next type's `MethodList` index is 123, the logic in the lines above the quoted line computes the end index as 122 because it subtracts 1.

**Comment by malwarefrank** [comment]
Thank you for the bug report.  I am looking into it now
