### ISSUE TITLE
Use trusted publisher in workflow

### ISSUE THREAD

**Issue by malwarefrank** [malwarefrank/dnfile#81]
GitHub action recommends using a Trusted Publisher instead of API tokens in workflows to push to pypi.  And the pypi documentation strongly recommends using a GitHub environment.

https://docs.pypi.org/trusted-publishers/using-a-publisher/

**Comment by williballenthin** [comment]
we enabled this for capa in this PR: https://github.com/mandiant/capa/pull/1613/files

ultimately it was about as easy as the blog post said, which is amazing.

**Comment by malwarefrank** [comment]
thanks for the heads-up.  Made the changes in b837ad6 and just need to test

**Comment by malwarefrank** [comment]
Looks like it's working

**Comment by malwarefrank** [comment]
looks like it's working
